zookeeper:
  image: srob/zookeeper
  expose:
    - 2181
  ports:
    - 2181:2181

kafkanode1:
  image: srob/kafka
  environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper
  links:
    - zookeeper:zookeeper
  ports:
    - 9092

kafkanode2:
  image: srob/kafka
  environment:
    - KAFKA_BROKER_ID=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper
  links:
    - zookeeper:zookeeper
  ports:
    - 9092

kafkanode3:
  image: srob/kafka
  environment:
    - KAFKA_BROKER_ID=3
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper
  links:
    - zookeeper:zookeeper
  ports:
    - 9092

schemaregisty1:
  image: srob/schema-registry
  environment:
    - SCHEMA_KAFKASTORE_CONNECTION_URL=zookeeper:2181
  links:
    - zookeeper:zookeeper
  ports:
    - 8081:8081
  expose:
    - 8081

schemaregisty2:
  image: srob/schema-registry
  environment:
    - SCHEMA_KAFKASTORE_CONNECTION_URL=zookeeper:2181
  links:
    - zookeeper:zookeeper
  expose:
    - 8081

schemaregisty3:
  image: srob/schema-registry
  environment:
    - SCHEMA_KAFKASTORE_CONNECTION_URL=zookeeper:2181
  links:
    - zookeeper:zookeeper
  expose:
    - 8081
