#!/bin/bash

: ${SCHEMA_KAFKASTORE_CONNECTION_URL:=localhost:2181}
: ${SCHEMA_HOST_NAME:=`hostname -i`}

export SCHEMA_KAFKASTORE_CONNECTION_URL
export SCHEMA_HOST_NAME

echo '# Generated by schema-registry-docker.sh' > /etc/schema-registry/schema-registry.properties

for var in $(env | sort | grep '^SCHEMA_'); do
    key=$(echo $var | sed -r 's/SCHEMA_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
    value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
    echo "${key}=${value}" >> /etc/schema-registry/schema-registry.properties
done

exec /usr/bin/schema-registry-start /etc/schema-registry/schema-registry.properties
